// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: grpcpb.proto

package GrpcPbExmpl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcPbExmplClient is the client API for GrpcPbExmpl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcPbExmplClient interface {
	Ping(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type grpcPbExmplClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcPbExmplClient(cc grpc.ClientConnInterface) GrpcPbExmplClient {
	return &grpcPbExmplClient{cc}
}

func (c *grpcPbExmplClient) Ping(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/GrpcPbExmpl/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcPbExmplServer is the server API for GrpcPbExmpl service.
// All implementations must embed UnimplementedGrpcPbExmplServer
// for forward compatibility
type GrpcPbExmplServer interface {
	Ping(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedGrpcPbExmplServer()
}

// UnimplementedGrpcPbExmplServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcPbExmplServer struct {
}

func (UnimplementedGrpcPbExmplServer) Ping(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGrpcPbExmplServer) mustEmbedUnimplementedGrpcPbExmplServer() {}

// UnsafeGrpcPbExmplServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcPbExmplServer will
// result in compilation errors.
type UnsafeGrpcPbExmplServer interface {
	mustEmbedUnimplementedGrpcPbExmplServer()
}

func RegisterGrpcPbExmplServer(s grpc.ServiceRegistrar, srv GrpcPbExmplServer) {
	s.RegisterService(&GrpcPbExmpl_ServiceDesc, srv)
}

func _GrpcPbExmpl_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcPbExmplServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcPbExmpl/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcPbExmplServer).Ping(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcPbExmpl_ServiceDesc is the grpc.ServiceDesc for GrpcPbExmpl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcPbExmpl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcPbExmpl",
	HandlerType: (*GrpcPbExmplServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GrpcPbExmpl_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcpb.proto",
}
